### ISSUE TITLE
Crypto: use authenticated encryption

### ISSUE THREAD

**Issue by dchest** [RoxasShadow/EDB#1]
CBC mode doesn't authenticate and is [malleable](https://en.wikipedia.org/wiki/Malleability_(cryptography)). You should use authenticated encryption, for example, by authenticating encrypted data with HMAC-SHA-256 using a separate key or using an authenticated encryption mode, such as AES-GCM.

**Comment by dchest** [comment]
I'd argue this is deserves a "bug" label rather than "enhancement", because attackers (e.g. someone with access to the user's S3) can modify backups without users noticing it.

**Comment by RoxasShadow** [comment]
Good point, the "bug" label is more suitable for this :+1:

**Comment by dchest** [comment]
BTW, since you now use HKDF, you can derive authentication (for HMAC) and encryption key (for AES-CBC) from the single key provided by user:

```ruby
kdf = HKDF.new(s)
encryptionKey = kdf.next_bytes(32)  # what we currently do
authenticationKey = kdf.next_bytes(32) # next 32 bytes are auth key
```

Then run HMAC with `authenticationKey` over encrypted data + IV and append the result to encrypted text. Before decrypting, first run HMAC again and verify that it matches the appended one (verification should be constant time, not simple string comparison), and then, if verified successfully, decrypt.

**Comment by RoxasShadow** [comment]
#9 has been merged. Thank you again for your help!
