### ISSUE TITLE
Crypto: CBC mode has all-zero initialization vector

### ISSUE THREAD

**Issue by dchest** [RoxasShadow/EDB#2]
Since `iv` option is not set, OpenSSL uses all-zero IV, which is not secure. Use [random_iv](http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html#method-i-random_iv) to generate a new random IV, and then append or prepend it (unencrypted) to the encrypted data, so that you can read it and set during decryption.

**Comment by RoxasShadow** [comment]
Good point, thank you for reporting this issue.

**Comment by RoxasShadow** [comment]
Merged #7 so I'm closing this. I'm ready to open this again if there's something that seems not quite good to you.
