### ISSUE TITLE
Crypto: key string is used directly as AES key

### ISSUE THREAD

**Issue by dchest** [RoxasShadow/EDB#3]
In the example config the key is an ASCII string and it's used directly as a key, but AES key should better be a uniform random-like byte sequence. Use HKDF or a simple SHA256 of this string to derive the appropriate key. Alternatively, require a base64-encoded string of 256-bit key and decode it before setting it as AES key.

**Comment by RoxasShadow** [comment]
That string was supposed to be generated by the user by using a random string generator as I highlighted in the README (> `remember also to change the secret`).

I don't know if hashing the given key would be worth. Maybe we could add a key generator instead inside the executable that could suite well to the user's perception of knowing what he/her's doing.

**Comment by dchest** [comment]
The thing is, that regardless of how it's generated, it's an ASCII string in YAML, but AES key is a byte string, which needs uniform bytes from 0 to 255. For example, your sample key only uses 62 characters (`0-9,A-z`) so its effective security is only `log(62) * 32 ~= 190 bits`, which, while not something to worry about, is far from the promised 256, and knowing that the key character space is limited may allow some future attacks. In short, a block cipher key should be a uniform random-like sequence, for this you'll need to use binary data in YAML (``--- !binary ...`), or use base64/hex encoding directly, or allow for longer strings, which are hashed to get the real key (e.g. 43 random characters from 62-character space will have ~256 bits of entropy, which you'll hash with SHA256 to get the 32-byte key).

Yes, having a key generator would be great.

**Comment by RoxasShadow** [comment]
I think we can close this. Thank you again!
